variables:
  buildConfiguration: 'Release'
  netSdkVersion: '9.x'

jobs:
- job: BuildAndRunCodeAnalysis
  displayName: Build and run code analysis
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: Set up .NET SDK
    inputs:
      version: $(netSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build solution with code analysis
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: -c $(buildConfiguration) -warnaserror

- job: RunTestsOnWindowsAndMacOS
  displayName: Run tests on
  strategy:
    matrix:
      macOS:
        imageName: 'macOS-latest'
      Windows:
        imageName: 'windows-latest'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UseDotNet@2
    displayName: Set up .NET SDK
    inputs:
      version: $(netSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -p:RunAnalyzers=false
  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    timeoutInMinutes: 3
    inputs:
      command: test
      projects: 'test/*/*.UnitTests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.codecoverage.runsettings" --no-build
  - task: DotNetCoreCLI@2
    displayName: Run integration tests
    condition: succeededOrFailed()
    timeoutInMinutes: 5
    inputs:
      command: test
      projects: 'test/*/*IntegrationTests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build

- job: RunTestsOnUbuntu
  displayName: Run tests on Ubuntu
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UseDotNet@2
    displayName: Set up .NET SDK
    inputs:
      version: $(netSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '*.sln'
      arguments: -c $(buildConfiguration) -p:RunAnalyzers=false
  - script: sudo npm install -g html-validate
    displayName: Install html-validate NPM package
  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    timeoutInMinutes: 3
    inputs:
      command: test
      projects: 'test/*/*.UnitTests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.codecoverage.runsettings" --no-build
  - task: DotNetCoreCLI@2
    displayName: Run integration tests
    condition: succeededOrFailed()
    timeoutInMinutes: 5
    inputs:
      command: test
      projects: 'test/*/*IntegrationTests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build
